\documentclass[10pt]{article}
\usepackage{natbib}
\usepackage[english]{babel}
\begin{document}
\SweaveOpts{concordance=TRUE}

%\title{Predator phylogenetic diversity decreases predation rate via
%  antagonistic interactions} 
%\author{A. Andrew M. MacDonald, Diane
%  S. Srivastava, Gustavo Q. Romero}
%\begin{spacing}{2}
%\maketitle

<<echo=FALSE>>=
## load libraries
library(picante)

## load phylogenetic data:
predtree <- read.tree("../TreeData/predators.arbit.ultrametric.phy")
@

\section{Methods}

% Introduction themes related to this: the presence/rarity of food web
% quantifications.  the large variation in ecosystem function (decomp
% rate) in bromeliads in this habitat (lecraw, unpub data).  does pred
% pd account for some of this? 


We combined predators together in species pairs that represented a
range of relatedness: congeners (two congeneric damselflies,
\emph{Leptagrion andromache} and \emph{Leptagrion elongatum}), two
insects (a damselfly, \emph{Leptagrion elongatum} and a predatory fly
(Diptera: Tabanidae)) and two invertebrates (\emph{L. elongatum} and
leeches).  We also included these four species in monoculture, along
with a predator-free control (8 treatments, n=5).  Combinations were
substitutive, maintaining the same amount of predator metabolic
capacity (biomass raised to the power of 0.69, predicting the scaling
of metabolism with body mass \citep{Brown2004}) in each.  Response
variables included the rate of decomposition of leaves, bromeliad
growth and insect emergence.  This experiment allows the estimation of
the effect of each predator species from monoculture treatments, as
well as the detection of non-additive effects in predator
combinations.

In Feburary 2011, bromeliads between 90 and 200ml were collected,
thoroughly washed and soaked for 12 hours in a tub of water.  They
were then hung for 48 hours to dry.  One bromeliad dissected after
this procedure contained no insects.

Each bromeliad was supplied with dried leaves, simulating natural
detritus inputs from the canopy.  We enriched these leaves with N-15
by fertilizing five (Jabuticaba, \emph{Genus species}) plants with
40ml/pot/day of 5g/L ammonium sulphate containing 10 percent atom
excess of N15. %%duration. started on 27/1/2011
Whole leaves were then picked from plants and air-dried until constant
weight, and then soaked for three days and the water discarded.  About
1.5 g of leaves were placed in each bromeliad.

Each bromeliad was stocked with a representative insect community.
The densities of each prey taxon were calculated from a 2008
observational dataset, using data from bromeliads of similar size to
those in our experiment (DS Srivastava, upub. data).  All densities
used were within the range of these calculated abundances, and all
experimental bromeliads received the same insect community.  Halfway
through the experiment, insects were added to bromeliads a second
time.

\begin{table}
  \centering
  \caption{densities of each species}
  \label{tab:sppden}
  \begin{tabular}{l l}
    \hline
    \emph{Chironomus detriticula} & 10 \\
    \emph{Polypedium} sp. 1 & 4 \\
    \emph{Polypedium} sp. 2 & 2 \\
    \emph{Psychodid} sp. 1 & 1 \\
    \emph{Scyrtes} sp. A & 5 \\
    \emph{Culex} spp. & 4 \\
    \emph{Trentepholia} sp. & 1
  \end{tabular}
\end{table}


% Densities were calculated from 2008 dataset survey in two ways: the
% first, by poisson regression and the second, by taking the average of
% all bromeliads in between 90 and 200ml (n = 6???). 

After addition of the prey community, all bromeliads were enclosed
with a mesh cage and checked daily for emergence of adults.

%% how much fine detritus was added?

%% exactly how much coarse was added?  mean and standard deviations
%% for each.

%% Exactly when was the second addition of the larvae?

%%%% must add in the hypotheses section from Proposal.tex - but not to
%%%% keep it as a bullet list!  or just keep in the specific
%%%% hypotheses tested?


%\linenumbers

\begin{figure}
\begin{center}
<<fig=TRUE,echo=FALSE>>=
plot(predtree)
@
\end{center}
\caption{Taxonomic relationships among all the predator taxa which coexist in the Cardoso fieldsite.}
\label{fig:one}
\end{figure}


%\end{spacing}
\bibliography{../references/references.bib}
\end{document}